### ISSUE TITLE
[Request] Try loading an extension on file change instead of reloading if the initial load failed

### ISSUE THREAD

**Issue by SolsticeShard** [robertwayne/cogwatch#15]
Definitely a bit of an edge case on this one, but a good nice-to-have!

For example, if you create a new empty file in your watch directory, it will trigger an Added event (which understandably fails to load the extension). However subsequent changes to that file (making it a valid extension) will permanently fail; the extension was never loaded, and Changed events trigger an extension reload which fails if the extension was never loaded in the first place.

I think changing around line 91 of cogwatch.py would be the key here, checking to see if the extension is currently loaded (via bot.extensions) and either calling load or reload based on that.

This is mostly just a nicety during dev for quick iteration as I'm often creating new files and iterating on them until they become a valid extension, so I don't think this is crucial at all for production deployments.

**Comment by robertwayne** [comment]
Yeah - this makes sense. I intended to have it handle these cases previously, but when dpy stopped development I never got around to fixing it.

I will add this into the next release.
