### ISSUE TITLE
add py-cord support

### ISSUE THREAD

**Issue by fthomys** [robertwayne/cogwatch#21]
Library: https://github.com/Pycord-Development/pycord

could you add support for it?

**Comment by robertwayne** [comment]
I'm good with this. I'll accept a PR if you're interested. If not, I'll take a look when I can. :)

**Comment by Tdarnell** [comment]
Should be closed with #27 although pycord is untested as I don't use it, would be worth checking it works as expected after adding it to the imports.

**Comment by robertwayne** [comment]
This is available in v3.2.0 now.
