### ISSUE TITLE
Slight error in example

### ISSUE THREAD

**Issue by ThomasJRyan** [robertwayne/cogwatch#23]
https://github.com/robertwayne/cogwatch/blob/e3037fe0a19ce93ab322bea9545e99febf716c35/examples/subclassed_bot.py#L12

I might be incorrect as I haven't tested it verbatim, but when I was implementing this into my bot and using the subclassed_bot as a reference, I noticed that `preload` wasn't set to `True` and there doesn't appear to be anything that loads `ping` initially.

I'm not certain if this is a mistake or if I missed something obvious. Apologies if it's the latter

**Comment by robertwayne** [comment]
Yeah, that should probably be set to True to represent a fully stand-alone example.

Thanks for pointing it out.
