### ISSUE TITLE
Add instructions about required "setup" function on cog extensions

### ISSUE THREAD

**Issue by EmoonX** [robertwayne/cogwatch#9]
As I was getting myself acquainted with cogwatch (and Cogs themselves), unfortunately, I lost quite some time dealing with extension-related errors upon trying to reload a cog file; until finding out I needed to add the following function at the bottom of it:

```python
def setup(bot: commands.Bot):
    '''Add cog every time extension (module) is (re)loaded.'''
    bot.add_cog(MyCog(bot))
```

However, there is no explicit reference to the Extension concept in cogwatch tutorial, even though [discord.py extensions page](https://discordpy.readthedocs.io/en/latest/ext/commands/extensions.html) mentions _hot-reloading_. Since it seems to be a lower-level concept that many users that arrive here aren't aware of (myself included), I think it might be interesting to add tutorial instructions regarding these points (especially the needed `setup` function). :slightly_smiling_face:

**Comment by robertwayne** [comment]
Thanks for the feedback!

I've added a complete example to the `examples` directory that should help guide developers unfamiliar with the cog concept in the future!
